name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: ["master", "main", "qa"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
      actions: read
      pull-requests: read

    steps:
      - name: Generate display1.svg
        uses: lowlighter/metrics@latest
        with:
          filename: display1.svg
          token: ${{ secrets.METRICS }}
          committer_message: "chore: update display1 metrics"
          user: hanzel-sc
          template: classic
          config_timezone: Asia/Kolkata

          base: header, activity, community, repositories, metadata
          base_indepth: yes
          base_hireable: yes

          repositories_affiliations: owner, collaborator, organization_member
          repositories_forks: no
          repositories_batch: 100
          repositories_indepth: yes

          plugin_lines: yes
          plugin_lines_history_limit: 5
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          
          plugin_followup: yes
          plugin_followup_sections: repositories

          plugin_activity: yes
          plugin_activity_days: 90
          plugin_activity_filter: all
          plugin_activity_limit: 10
          plugin_activity_load: 1000
          plugin_activity_visibility: public, private

          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 90
          plugin_habits_facts: yes
          plugin_habits_from: 600
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 21
          plugin_languages_recent_load: 600
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

      - name: Generate display2.svg
        uses: lowlighter/metrics@latest
        with:
          filename: display2.svg
          token: ${{ secrets.METRICS }}
          committer_message: "chore: update display2 metrics"
          base: ""
          config_timezone: Asia/Kolkata

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_leetcode: yes
          plugin_leetcode_user: Hanzel_sc
          plugin_leetcode_sections: solved, skills, recent
          plugin_leetcode_limit_recent: 5
          plugin_leetcode_limit_skills: 14

          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following

          plugin_stars: yes
          plugin_stars_limit: 6
